### ISSUE TITLE
Practica

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/practica-de-requisitos-team-pro#1]
[Practica.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-requisitos-team-pro/files/7585541/Practica.pdf)

**Comment by JazminloRI** [comment]
CAL: 86

**Comment by josealfredo79** [comment]
Se puede aplicar una regla de 3 para sacar el porcentaje de la practica que su valor es de 30%

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/143171576-992101f6-d95e-43d8-aa29-ad21a93dd48f.png)
Esta lista de requisitos se debe revisar para mejorar su redaccion

**Comment by josealfredo79** [comment]
OBJETIVO DEL SISTEMA.
Objetivo del sistema es gestionar la información de la compra – venta de casas, terrenos, edificios
o cualquier tipo de inmueble mediante una aplicación.

Nuevamente este objetivo debe estar bien redactado...

**Comment by JazminloRI** [comment]
CAL: 25.8%

**Comment by josealfredo79** [comment]
La redaccion correcta Brindar informacion al usuario sobre la utilización del sistema

**Comment by josealfredo79** [comment]
La redacción correcta es Registrar la venta de un producto o servicio o suscripcion

**Comment by josealfredo79** [comment]
Registrar la agenda de la visita de un bien

**Comment by DuilioAquino10** [comment]
[Practica-.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-requisitos-team-pro/files/7622135/Practica-.pdf)

**Comment by DuilioAquino10** [comment]
[Practica-Corregida.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-requisitos-team-pro/files/7622635/Practica-Corregida.pdf)

**Comment by josealfredo79** [comment]
Ya corrigieron, gracias...Bien hecho y revisado
